### PR TITLE
Restore function and support for aws regions added

### PR DESCRIPTION
**Pull request by ghost**
- Adds restore script that will restore the latest backup if the RESTORE variable is set to true.
- Adds support for aws s3 regions.

### CODE REVIEW

**Comment by borjaburgos** [comment]
Wow! This is great! Lots of awesome changes. Want to add yourself to the Dockerfile as a MAINTAINER? I'll merge after that :smile: 

Thanks!

**Comment by borjaburgos** [comment]
Thanks again!

**Comment by ghost** [comment]
No problem, thanks for merging.

I will properly add support for setting backup expiration (lifecycle) next. However it might take a few days as I need to read up on how that works first.

Features I think this needs are:
- auto restore, (mostly a convenience feature).
- support for other storage providers, google cloud, azure, private server, etc... (can be really important to respond to price changes quickly, and will allow locating backup at same provider used for docker hosts).
- lifecycle/expiration, (needs to be in there early to prevent a storage nightmare later).
- report/alerts/monitoring, (some way of knowing if the backup run was a success or failure).

Let me know what you think of this plan?

**Comment by Ramblurr** [comment]
I'd love to see lifecycle/expiration supported!

**Pull request merged**
