### PR TITLE
fix 1 liner for find latest backup

### PR DESCRIPTION
**Pull request by odk211**
current script do not work when "aws s3 ls" shows such as below.

```
2015-02-12 17:42:28  492667043 cassandra.2015-02-12-08-39-12.tar.gz
2015-02-12 21:52:44        328 elasticsearch.2015-02-12-12-52-39.tar.gz
```

I can not find elasticsearch.2015-02-12-12-52-39.tar.gz.
So I use awk.

### CODE REVIEW

**Comment by ghost** [comment]
yep, ran in to the same problem yesterday.

**Comment by odk211** [comment]
@borjaburgos Hello, Can you merge this PR ?

**Comment by sunshineo** [comment]
Can someone merge this?

**Comment by sunshineo** [comment]
Awesome, I can stop using someone's fork now.

**Comment by odk211** [comment]
@borjaburgos Sorry I forgot that I send the pull request, so I commit some another one...
If you do not want my commit, please revert it.

**Pull request merged**
