### PR TITLE
Cron to do routine backups

### PR DESCRIPTION
**Pull request by cggaurav**
@tifayuki  With a conditional if CRON_TIME is set.

### CODE REVIEW

**Comment by ahfeel** [comment]
:+1:

**Comment by tifayuki** [comment]
Thank you

**Comment by olivergrahl** [comment]
Be careful! This will fill up your disk over time, because the container will not be removed after running a backup. Since backup.sh does not remove the locally saved tarball, it will collect all tarballs that have ever been sent to S3. See my [PR](https://github.com/tutumcloud/dockup/pull/20).

**Comment by replaid** [comment]
This doesn't provide the same environment as the backup script would otherwise see. See #23.

**Pull request merged**
